FROM ubuntu:22.04

ENV WORKLOAD=''
ENV MODELS=''
ENV TYPE=''
ENV ENDPOINT=''
ENV ACCESS_KEY=''
ENV SECRET_KEY=''
ENV IMAGE_BUCKET=''
ENV CLASSES_BUCKET=''
ENV KUBE_VERSION 1.27.5
ENV PYTHON_VERSION=3.10

WORKDIR /config

RUN apt-get update -y && apt-get install -y ca-certificates bash  git curl dnsutils podman wget \ 
    && wget -q https://storage.googleapis.com/kubernetes-release/release/v${KUBE_VERSION}/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl \
    && chmod +x /usr/local/bin/kubectl  && chmod g+rwx /root && chmod g+rwx /config

RUN apt-get install -y python${PYTHON_VERSION} python3-pip vim

RUN wget -qO /usr/local/bin/mc https://dl.min.io/client/mc/release/linux-amd64/mc \
    && chmod a+x /usr/local/bin/mc

COPY requirements.txt .
RUN pip install -r /config/requirements.txt
RUN mkdir -p /config/k8s_infer

COPY . /config/

CMD ["/bin/bash", "-c", "/config/start.sh"]