apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-infer-pvc
  namespace: s3
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
