apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alexnet-batch-job-pvc
  namespace: jenkins
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
