apiVersion: batch/v1
kind: Job
metadata:
  name: k8s-infer-renset18-googlenet-job
  namespace: s3
spec:
  template:
    metadata:
      labels:
        app: k8s-infer-renset18-googlenet-0job
    spec:
      containers:
      - name: k8s-infer
        image: dbha/k8s-infer-cli-image:3
        env:
        - name: WORKLOAD
          value: "C"  # C or L
        - name: TYPE
          value: "S3"        
        - name: MODELS
          value: "resnet18,googlenet"
        - name: ENDPOINT
          value: "minio-svc.minio-dev:9000"
        - name: ACCESS_KEY
          value: "pxLFj7m4sFiLj7GZaOsA"
        - name: SECRET_KEY
          value: "bGatyb2DFTb942EzxJJ0fbhE5CslwBt5joFzFi4Y"
        - name: IMAGE_BUCKET
          value: "images"
        - name: CLASSES_BUCKET
          value: "imagenet-classes"
      restartPolicy: Never        
