apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: resnet-googlenet-batch-job-pvc
  namespace: jenkins
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
